### ISSUE TITLE
Error when linking: cannot find `-lGLEW`

### ISSUE THREAD

**Issue by musiclistener2** [8dcc/tf2-cheat#12]
when building the code with ```make -j$(nproc)``` it gives error 
```
gcc -Wall -Wextra -Ofast -m32 -fPIC -shared -o libenoch.so obj/main.c.o obj/sdk.c.o obj/globals.c.o obj/hooks.c.o obj/util.c.o obj/settings.c.o obj/menu.c.o obj/dependencies/cJSON/cJSON.c.o obj/features/esp.c.o obj/features/chams.c.o obj/features/aim/aimbot.c.o obj/features/aim/meleebot.c.o obj/features/aim/medigun.c.o obj/features/antiaim.c.o obj/features/movement.c.o obj/features/misc.c.o obj/features/visuals.c.o obj/features/prediction.c.o obj/features/auto_detonate_stickies.c.o -lm -lSDL2 -lGLEW
/usr/bin/ld: skipping incompatible /usr/lib/x86_64-linux-gnu/libGLEW.so when searching for -lGLEW
/usr/bin/ld: skipping incompatible /usr/lib/x86_64-linux-gnu/libGLEW.a when searching for -lGLEW
/usr/bin/ld: cannot find -lGLEW: No such file or directory
/usr/bin/ld: skipping incompatible /usr/lib/x86_64-linux-gnu/libGLEW.so when searching for -lGLEW
collect2: error: ld returned 1 exit status
make: *** [Makefile:39: libenoch.so] Error 1
```
I have done everything by the guide, but I also noticed that ``` sudo apt install libglew-dev:i386 libsdl2-dev:i386 gcc-multilib ```
gives ``` E: Unable to locate package libglew-dev:i386 ``` error
though i installed the package manually

**Comment by 8dcc** [comment]
> ```
> /usr/bin/ld: skipping incompatible /usr/lib/x86_64-linux-gnu/libGLEW.so when searching for -lGLEW
> /usr/bin/ld: skipping incompatible /usr/lib/x86_64-linux-gnu/libGLEW.a when searching for -lGLEW
> ```

Although you installed GLEW, you didn't install the 32-bit version of the library. I don't currently have a debian-based machine, so I can't really help you with the dependencies.

Maybe @s6fty can help you, since he made those changes to the README (#3).

**Comment by sumdudinhell** [comment]
I have the same issue, and since the apt command gives the same error I downloaded libglew-dev instead.

**Comment by 8dcc** [comment]
> libglew-dev dropped 32-bit support since the release of ubuntu 20.04.1.

Oh... Maybe you need to manually update your `/etc/apt/sources.list`?

Either way, I found [this](https://www.ubuntuupdates.org/package/core/mantic/universe/base/libglew-dev) link where you seem to be able to download the [32-bit `.deb` file](http://security.ubuntu.com/ubuntu/pool/universe/g/glew/libglew-dev_2.2.0-4_i386.deb).

You should be able to manually install the package from that file using:
```console
$ sudo dpkg -i libglew-dev_2.2.0-4_i386.deb
$ sudo apt-get install -f  # Not sure if this is needed
```

**Comment by sumdudinhell** [comment]
Sadly, the 32-bit .deb file link just gives me an 404 not found error... In theory these cheats would work perfectly in an older version of ubuntu, like 18.04.

**Comment by s6fty** [comment]
> Sadly, the 32-bit .deb file link just gives me an 404 not found error...
have you tried
```
dpkg --print-foreign-architectures
```
and see if i386 is supported, if so:
```
$ sudo dpkg --add-architecture i386
$ sudo apt-get update
```
and try installing it again

**Comment by sumdudinhell** [comment]
Yes, i386 is supported, `dpkg --print-foreign-architectures` return `i386`. What I mean by the link is that I can't seem to open it. Take a look:
![look](https://github.com/8dcc/tf2-cheat/assets/152049532/06212d99-2283-49f8-919e-6f57f71e7188)

I also found [this link](https://launchpad.net/ubuntu/bionic/i386/libglew-dev/2.0.0-5), with an downloadable [.deb file](http://launchpadlibrarian.net/334512723/libglew-dev_2.0.0-5_i386.deb), but there's conflicts with it so I can't install it.

**Comment by s6fty** [comment]
@sumdudinhell im assuming you are on ubuntu, which doesnt have i386 files. try installing from debian's page
https://packages.debian.org/sid/i386/libglew-dev/download

**Comment by sumdudinhell** [comment]
> im assuming you are on ubuntu, which doesnt have i386 files. try installing from debian's page
https://packages.debian.org/sid/i386/libglew-dev/download

Same luck, dependency problems:

Selecting previously unselected package libglew-dev:i386.
(Reading database ... 344077 files and directories currently installed.)
Preparing to unpack libglew-dev_2.2.0-4+b1_i386.deb ...
Unpacking libglew-dev:i386 (2.2.0-4+b1) ...
dpkg: dependency problems prevent configuration of libglew-dev:i386:
 libglew-dev:i386 depends on libglew2.2 (= 2.2.0-4+b1).

dpkg: error processing package libglew-dev:i386 (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 libglew-dev:i386

**Comment by s6fty** [comment]
> libglew-dev:i386 depends on libglew2.2 (= 2.2.0-4+b1).

if you have libglew2.2 can you remove it and try again?

**Comment by sumdudinhell** [comment]
> if you have libglew2.2 can you remove it and try again?
I've tried that, but it doesn't work

**Comment by sumdudinhell** [comment]
I finally managed to make it work. You have to install it manually, by extracting the deb file and moving their components to where they belong. It's not very tedious though, because the deb file has very few components. Won't shave off a lot of your time.

**Comment by sumdudinhell** [comment]
Compiling works, but running the sh file gives:
`sudo ./inject.sh
ERROR: inject.sh: process not running.
`

**Comment by 8dcc** [comment]
> Compiling works, but running the sh file gives: `ERROR: inject.sh: process not running.`

Please make sure the game is running and you are not running steam from flatpak. If the problem persists, please make a separate issue.

**Comment by sumdudinhell** [comment]
> Please make sure the game is running and you are not running steam from flatpak. If the problem persists, please make a separate issue.

dumb me, i didn't even know that

**Comment by s6fty** [comment]
i booted into ubuntu and did some further research, there is an easier way to install it. here are the commands:
```
echo "deb http://archive.ubuntu.com/ubuntu bionic-updates universe
deb http://archive.ubuntu.com/ubuntu bionic universe" | sudo tee -a /etc/apt/sources.list.d/bionic.list

sudo apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 3B4FE6ACC0B21F32

sudo apt update

sudo apt install libglew-dev:i386

sudo rm /etc/apt/sources.list.d/bionic.list

sudo apt update
```

what this does is it adds ubuntu bionic repository to the system, adds the GPG key because its unsigned (this might be different for everyone pls let me know if it didnt work for you), install 32-bit version of libglew-dev, uninstall the bionic repository from system and update it so it doesnt mess with system.

problem was with the new ubuntu, it doesnt provide 32-bit version of libglew-dev so we have to either manually install or add older repository like this. i might make a little script for building in ubuntu/debian based distros in the future even though i mainly use arch.

**Comment by sumdudinhell** [comment]
just tested @s6fty 's solution out. it didn't work. so, i guess the only way to make it compile is by installing the package manually

**Comment by sumdudinhell** [comment]
@s6fty it didn't work :( i checked the usr directory, there was no glew package, which is weird as hell

**Comment by sumdudinhell** [comment]
> @sumdudinhell im assuming you are on ubuntu, which doesnt have i386 files. try installing from debian's page https://packages.debian.org/sid/i386/libglew-dev/download

this works by installing manually, i think the modified commands of @s6fty can install the package

**Comment by throw198333** [comment]
> i booted into ubuntu and did some further research, there is an easier way to install it. here are the commands:
> 
> ```
> echo "deb http://archive.ubuntu.com/ubuntu bionic-updates universe
> deb http://archive.ubuntu.com/ubuntu bionic universe" | sudo tee -a /etc/apt/sources.list.d/bionic.list
> 
> sudo apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 3B4FE6ACC0B21F32
> 
> sudo apt update
> 
> sudo apt install libglew-dev:i386
> 
> sudo rm /etc/apt/sources.list.d/bionic.list
> 
> sudo apt update
> ```
> 
> what this does is it adds ubuntu bionic repository to the system, adds the GPG key because its unsigned (this might be different for everyone pls let me know if it didnt work for you), install 32-bit version of libglew-dev, uninstall the bionic repository from system and update it so it doesnt mess with system.
> 
> problem was with the new ubuntu, it doesnt provide 32-bit version of libglew-dev so we have to either manually install or add older repository like this. i might make a little script for building in ubuntu/debian based distros in the future even though i mainly use arch.

this worked on fixing my issues, thank you

**Comment by 8dcc** [comment]
Closing this issue as completed, re-open it if needed.
