### ISSUE TITLE
Auto rocket jump is broken

### ISSUE THREAD

**Issue by sumdudinhell** [8dcc/tf2-cheat#16]
you can press right mouse button, but it won't rocket jump, even with the default rocket launcher. did the ps1 graphics update mess it up?

**Comment by 8dcc** [comment]
It works fine for me, even with that setting enabled.


https://github.com/8dcc/tf2-cheat/assets/29655971/e7c2f8f6-5bc4-4acf-8016-a6734025cffe

**Comment by sumdudinhell** [comment]
interesting. let me download it again to see if it works

**Comment by sumdudinhell** [comment]
nope, just reinstalled the cheat but it still doesn't work. here i tried to rocket jump with mouse2, then proceeded to rocket jump manually.

https://github.com/8dcc/tf2-cheat/assets/152049532/70d3c407-f199-4a26-8594-053f5661348f

**Comment by 8dcc** [comment]
> here i tried to rocket jump with mouse2, then proceeded to rocket jump manually.

So the cheat did shoot that first rocket? Or was that you?

**Comment by sumdudinhell** [comment]
no, i shot that first rocket, then pressed mouse2

**Comment by sumdudinhell** [comment]
oh wait... i checked the cheat's files and realized that it uses secondary attack as input for the rocketjump. since i use a laptop, i unbound mouse2 to secondary attack and instead bound q to secondary attack. dangit i'm just as dumb as soldier lmao

**Comment by 8dcc** [comment]
Okay, then I need you to put a breakpoint in the `autorocketjump` function.

Compile the cheat using:
```bash
sudo make clean debug inject
```

And once it's loaded, press `Ctrl+C` inside the terminal where you injected the cheat, and put the following lines into the prompt:
```bash
(gdb) break movement.c:94
Breakpoint 1 at 0xdbfe69af: file src/features/movement.c, line 94.
(gdb) continue
Continuing.
```

Then, try the autorocketjump in-game and let me know if the game freezes, and the prompt changes to:

```bash
Thread 1 "hl2_linux" hit Breakpoint 2, autorocketjump (cmd=0x352d58c4) at src/features/movement.c:94
94      if (METHOD(g.localweapon, GetWeaponId) != TF_WEAPON_ROCKETLAUNCHER)
(gdb)
```

If it does, type in the prompt:

```bash
(gdb) break movement.c:97
Breakpoint 2 at 0xdbfe69c7: file src/features/movement.c, line 97.
(gdb) break movement.c:131
Breakpoint 3 at 0xdbfe6a69: file src/features/movement.c, line 132.
```

Then, continue two more times and paste the output of those commands here. It should look something like:
```bash
(gdb) continue
Continuing.

Thread 1 "hl2_linux" hit Breakpoint 2, autorocketjump (cmd=0x352d58c4) at src/features/movement.c:97
97      if (!can_shoot())
(gdb) continue
Continuing.

Thread 1 "hl2_linux" hit Breakpoint 3, autorocketjump (cmd=0x352d58c4) at src/features/movement.c:133
133     cmd->buttons |= IN_ATTACK | IN_DUCK | IN_JUMP;
(gdb)
```

**Comment by 8dcc** [comment]
> oh wait... i checked the cheat's files and realized that it uses secondary attack as input for the rocketjump. since i use a laptop, i unbound mouse2 to secondary attack and instead bound q to secondary attack. dangit i'm just as dumb as soldier lmao

Ah, sorry for not mentioning that. Thanks for taking the time to look at the source.

**Comment by sumdudinhell** [comment]
yeah sorry for wasting your time
