### ISSUE TITLE
permission denied? (cozettefonts)

### ISSUE THREAD

**Issue by lys0ul** [8dcc/tf2-cheat#20]
I got this when I unzipped cozettefonts:

```console
$ cp -R CozetteFonts /usr/share/fonts/truetype
cp: cannot create directory '/usr/share/fonts/truetype/CozetteFonts': Permission denied
```

And when I did `sudo ./inject.sh` via tf2-cheat, I am now getting this:
```
ERROR: inject.sh: font "CozetteVector" not found.
```

**Comment by nepcat** [comment]
You need root permissions to copy files into /usr/share/fonts/truetype directory, run copy command as sudo

`sudo cp -R CozetteFonts /usr/share/fonts/truetype`

**Comment by nepcat** [comment]
> > You need root permissions to copy files into /usr/share/fonts/truetype directory, run copy command as sudo
> > `sudo cp -R CozetteFonts /usr/share/fonts/truetype`
> 
> typed it in once, it says "command not found", then when i went to re-unzip i did it without sudo which came out with cp: cannot create regular file '/usr/share/fonts/truetype/CozetteFonts/CozetteVectorBold.otf': Permission denied i retyped it again with sudo and now it doesn't seem to do or say anything when i type it in either

`su root -c 'cp -R CozetteFonts /usr/share/fonts/truetype'`

**Comment by 8dcc** [comment]
> typed it in once, it says "command not found", then when i went to re-unzip i did it without sudo which came out with cp: cannot create regular file '/usr/share/fonts/truetype/CozetteFonts/CozetteVectorBold.otf': Permission denied i retyped it again with sudo and now it doesn't seem to do or say anything when i type it in either

I am not sure what you are saying. `sudo` is used to execute commands with root (admin) privilege. You need it because you are trying to copy the "CozetteFonts" folder into a folder which your user can't access.

You can unzip the file whenever you want (e.g. `~/Downloads`) and then move the extracted folder to the path using `sudo cp ...`.

If sudo is not installed on your machine (which is weird, since most popular "plug-and-play" distributions have it installed), you can use `su -c "..."` as @nepcat said. Note that the quotes (either simple or double) are important.

**Comment by lys0ul** [comment]
> su root -c 'cp -R CozetteFonts /usr/share/fonts/truetype'

"su: Authentication failure"
getting this whenever i type in my password

**Comment by lys0ul** [comment]
> If sudo is not installed on your machine (which is weird, since most popular "plug-and-play" distributions have it installed), you can use `su -c "..."` as @nepcat said. Note that the quotes (either simple or double) are important.

it's not in my downloads folder, and yes i do have sudo on my os

**Comment by 8dcc** [comment]
> > su root -c 'cp -R CozetteFonts /usr/share/fonts/truetype'
> 
> "su: Authentication failure" getting this whenever i type in my password

Keep in mind that this is not your user password, but the root password.

I am closing the issue because this is not the place to ask how to unzip and move a folder that is not even part of this project. Maybe you can ask in the [Cozette font](https://github.com/slavfox/Cozette) repo.
