### ISSUE TITLE
Aimbot smoothing is broken

### ISSUE THREAD

**Issue by sumdudinhell** [8dcc/tf2-cheat#22]
For context, aimbot smoothing only moves view after shooting, it isn't an issue with automatic firing weapons, but it is for other weapons (like the sniper rifle, shotgun, revolver, rocketlauncher, grenade launcher, etc.). 

ESP draws over crosshair, which makes sense since it's an external cheat, a possible solution would be to draw a crosshair along with ESP. 

For automedigun, if you keep healing the used-to-be best target and a target with lesser health comes, automedigun won't heal the other teammate. I suspect it's because it keeps attacking, but never actually stops attacking when another teammate comes. 

There's also an issue with autorocket jump not working with the direct hit because it has a different id, but I didn't mention it in the title because I have an autorocketjump bind now.

Edit: tidied my issue up because it's messy as hell.

**Comment by 8dcc** [comment]
> For context, aimbot smoothing only moves view after shooting, it isn't an issue with automatic firing weapons, but it is for other weapons (like the sniper rifle, shotgun, revolver, rocketlauncher, grenade launcher, etc.).

This should not be the case, as it shoots depending on the "Degree threshold" setting. If the target is within those degrees, it shoots. Try lowering the setting if you shoot too early.

https://github.com/8dcc/tf2-cheat/blob/d30345c9d9884affc124342ecf18de46562de330/src/features/aim/aimbot.c#L236-L244

>ESP draws over crosshair, which makes sense since it's an external cheat, a possible solution would be to draw a crosshair along with ESP.

Why do you think this is an external cheat? It is not. Also, I don't think this is an issue. 

>For automedigun, if you keep healing the used-to-be best target and a target with lesser health comes, automedigun won't heal the other teammate. I suspect it's because it keeps attacking, but never actually stops attacking when another teammate comes.

It does stop attacking, but I think this issue happens when `tf_medigun_autoheal` is 1. Try setting it to 0.

>There's also an issue with autorocket jump not working with the direct hit because it has a different id, but I didn't mention it in the title because I have an autorocketjump bind now.

I will try this later, I thought it worked.

**Comment by sumdudinhell** [comment]
i'll try it in tr_walkway when tf2 starts working again. dammit valve does really hate arch linux users

**Comment by sumdudinhell** [comment]
so, for updates, turning medigun autoheal worked, so that's done. 

however, aimbot smoothing still doesn't work, if i keep mouse1 pressed it tracks the target and is more likely to hit, but if i just tap mouse1 it almost always misses, even with no degree threshold. this even happens when smoothing is 1, which just snaps onto the target. 

and sorry for thinking this was an external cheat, i should've payed more attention to the fact that the cheat compiles into .so file. 

but ESP drawing over my crosshair is kinda annoying when there's a lot of people in a similar spot, and i can't see where i'm aiming. but if you don't wanna fix it, that's ok. 

since there were some updates to the main branch, i'll try to download it again to see if anything changes. i'll try to send you a video about it.

**Comment by sumdudinhell** [comment]
ok, now non-silent aimbot with no smoothing sometimes misses but most of the time it hits, but if i add a little smoothing it starts missing a lot

**Comment by 8dcc** [comment]
> > There's also an issue with autorocket jump not working with the direct hit because it has a different id, but I didn't mention it in the title because I have an autorocketjump bind now.
>
> I will try this later, I thought it worked.

You are right about this. I will fix it as soon as possible.

> ok, now non-silent aimbot with no smoothing sometimes misses but most of the time it hits, but if i add a little smoothing it starts missing a lot

For me, it is working fine. Note the "Degree threshold" setting.

https://github.com/8dcc/tf2-cheat/assets/29655971/36744e4f-e36d-41c5-b5e2-a3fbd9cedf99

**Comment by sumdudinhell** [comment]
by setting the on key option to true, it works, but not if it's off. also noticed that the lower the smoothing value, the more accurate it is. will send a video as soon as possible

**Comment by sumdudinhell** [comment]
https://github.com/8dcc/tf2-cheat/assets/152049532/144e9f73-8414-44e7-bddb-4f4b06596812

here, i try to snipe with the "on key" option on, and off. did it a ton of times to prove it wasn't a fluke. try it yourself.
