### ISSUE TITLE
Is this hacked client vac detected? 

### ISSUE THREAD

**Issue by throw198333** [8dcc/tf2-cheat#26]
I'm sure you can just solve this after you answer and I get its not a bug, but I'm honestly curious if this hacked client is vac detected or not. I know that fedorawave is as well as the free version of lmaobox.

**Comment by 8dcc** [comment]
This is not a "hacked client", it's a shared object (`.so`) that gets injected into the normal game process.

I just tried it, and it's currently not detected.
