### ISSUE TITLE
/tmp/libglxxxx.so: cannot open shared object file

### ISSUE THREAD

**Issue by uchuui** [8dcc/tf2-cheat#28]
![image](https://github.com/8dcc/tf2-cheat/assets/165387629/e600bcb1-ff13-4ef9-a62f-0a914e6c9a30)
from my understanding, it generates a string of random text each time for the 4 last characters of the .so file
it also seems that it can't find the file it just randomized and put in tmp.

i have triple checked that i have all of the dependencies installed.

**Comment by 8dcc** [comment]
Did you fix the issue?

In case you didn't, can you post the full output of `sudo make clean inject`?

The `inject.sh` script should echo the filename it generated. Can you also check that it's really in `/tmp/`?

**Comment by uchuui** [comment]
yeah. the issue is with flatpak containerisation.

i had steam installed through flatpak, it didn't work so i tried steam installed through AUR and it works.
