### ISSUE TITLE
"libGLEW.so.2.2: cannot open shared object file

### ISSUE THREAD

**Issue by Tira-tw** [8dcc/tf2-cheat#30]
$2 = 0x26a58450 "libGLEW.so.2.2: cannot open shared object file: No such file or directory"

**Comment by 8dcc** [comment]
You are posting no context and no information about your system, you just copy-pasted the error...

Do you have all the dependencies installed? Are you using flatpak or anything similar?

See also #12.

**Comment by 8dcc** [comment]
Closing the issue since, in any case, the game updated. See #32.
