### ISSUE TITLE
When using silent aimbot and moving player will move towards aimbot direction

### ISSUE THREAD

**Issue by nepcat** [8dcc/tf2-cheat#9]
How to reproduce: Go heavy, enable aimbot fov 180 & silent, move forward while aimbot is shooting at enemies. Player will move towards aimbot angle instead of actually walking forward.

**Comment by 8dcc** [comment]
This does not happen to me (using latest commit 444ce86712c1753305726a856d5837038633821e):

https://github.com/8dcc/tf2-cheat/assets/29655971/010e0a14-1538-4a63-80b9-12323af587fb

The function responsible for this is:

https://github.com/8dcc/tf2-cheat/blob/444ce86712c1753305726a856d5837038633821e/src/features/movement.c#L140-L160

And as you can see, the only thing it checks is if we are doing a taunt that allows movement.

**Comment by nepcat** [comment]
Using latest commit fixed this issue, alongside fixing broken esp & other stuff.
